import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and Conditions for using Scorovix, the FIFA World Cup 2026 predictions and live scores website.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms & Conditions | Scorovix',
    description: 'Terms and Conditions for using Scorovix.',
    url: 'https://www.scorovix.com/terms',
  },
};

const SECTIONS = [
  {
    h: 'Acceptance of Terms',
    p: 'By using Scorovix you agree to these terms. The site is provided for entertainment and informational purposes only.',
  },
  {
    h: 'About Our Predictions',
    p: 'All predictions are generated by AI using statistical analysis of real football data. Predictions are for entertainment purposes only and should not be used for gambling or betting decisions. Scorovix makes no guarantee of prediction accuracy.',
  },
  {
    h: 'Disclaimer',
    p: 'Scorovix is not affiliated with FIFA, any football association or any betting company. All World Cup data is sourced from third-party APIs. We make no warranty about the accuracy of live data.',
  },
  {
    h: 'Intellectual Property',
    p: 'All content on Scorovix including predictions, analysis and blog articles is owned by Scorovix. Do not reproduce without permission.',
  },
  {
    h: 'User Conduct',
    p: 'Users must not misuse the site, attempt to scrape data, or use predictions for commercial purposes without permission.',
  },
  {
    h: 'Privacy',
    p: 'We do not collect personal data. We use no cookies beyond essential site functionality. Contact contact@scorovix.com for privacy enquiries.',
  },
  {
    h: 'Changes to Terms',
    p: 'We may update these terms at any time. Continued use of the site means acceptance of the updated terms.',
  },
  {
    h: 'Contact',
    p: 'For questions about these terms: contact@scorovix.com',
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <h1 className="text-3xl font-bold sm:text-hero">Terms &amp; Conditions</h1>
      <p className="mt-2 text-sm text-text-secondary">Last updated: June 2026</p>

      <div className="mt-8 space-y-8">
        {SECTIONS.map((s, i) => (
          <section key={s.h}>
            <h2 className="text-cardtitle font-semibold text-text-primary">{i + 1}. {s.h}</h2>
            <p className="mt-2 leading-relaxed text-text-secondary">{s.p}</p>
          </section>
        ))}
      </div>

      <Link
        href="/"
        className="mt-10 inline-flex items-center gap-1 text-sm font-semibold text-gold transition-all hover:gap-2"
      >
        ← Back to Home
      </Link>
    </div>
  );
}
